### ISSUE TITLE
Two questions about datasets

### ISSUE THREAD

**Issue by yyf17** [facebookresearch/learning-audio-visual-dereverberation#2]
Thanks! Thanks for your excellent work and selfless disclosure of your code.
I have two questions about the dataset:
1) The main paper mentions "We generate 49,430/2,700/2,600 such samples for the train/val/test splits, respectively."
I found no val data in the data description section, only val-mini data, and val-mini only has 500 samples.
The first question is: how to get val data?
2) After downloading LibriSpeech, I found that the three suffixes *.csv files mentioned in the following code are missing (in line [300~305](https://github.com/facebookresearch/learning-audio-visual-dereverberation/blob/ef5ceb4b8fe59d10798628b7a4498c686473fd3d/vida/evaluator.py#L300) vida/evaluator.py )
The second question is: how to get these three files? Or how to deal with LibriSpeech to get these three files with the suffix *.csv?

**Comment by ChanganVR** [comment]
Hi @yyf17 sorry for the delay. For your questions:

1. we actually perform validation on val-mini since it seems like doing it for the full validation set is rather expensive.
2. not sure why you don't see these csv files but I uploaded these files here: https://drive.google.com/drive/folders/1KAQU8gsTQ2Zjz3-rIVXpvXZaJ5Iho7JQ?usp=sharing

Let me know if it works for you!

**Comment by yyf17** [comment]
@ChanganVR Thank you, work now.
